on: [push]

jobs:
  setup-exercism:
    runs-on: ubuntu-latest
    name: A job to download exercism
    steps:
      - uses: actions/checkout@v3
      - name: Set up exercism
        uses: ./
        with:
          token: ${{ secrets.EXERCISM_TOKEN }}
      - name: List files in working directory
        run: ls -a
      - name: Check exercism
        run: exercism
